##作者第二次更新的
##DBLP:
##  K: 5
##  emb_dim: 16
##  hidden: 64
##  input_drop: 0.4
##  dropout: 0.1
##  lr: 0.006
##  wd: 0.0
##  prop_lr: 0.002
##  prop_wd: 0.8
##
##ACM:
##  K: 5
##  emb_dim: 64
##  hidden: 256
##  input_drop: 0.85
##  dropout: 0.25
##  lr: 0.004
##  wd: 0.0
##  prop_lr: 0.05
##  prop_wd: 0.8
##
##IMDB:
##  K: 1
##  emb_dim: 128
##  hidden: 256
##  input_drop: 0.05
##  dropout: 0.7
##  lr: 0.0005
##  wd: 0.0005
##  prop_lr: 0.008
##  prop_wd: 0.0
##
##AMiner:
##  K: 5
##  emb_dim: 128
##  hidden: 32
##  input_drop: 0.2
##  dropout: 0.35
##  lr: 0.008
##  wd: 0.0005
##  prop_lr: 0.008
##  prop_wd: 0.3

#最开始的
#DBLP:
#  K: 5
#  emb_dim: 8
#  hidden: 8
#  input_drop: 0.4
#  dropout: 0.1
#  lr: 0.006
#  wd: 0.0
#  prop_lr: 0.002
#  prop_wd: 0.8
#
#ACM:
#  K: 5
#  emb_dim: 8
#  hidden: 8
#  input_drop: 0.85
#  dropout: 0.25
#  lr: 0.004
#  wd: 0.0
#  prop_lr: 0.05
#  prop_wd: 0.8

#IMDB:
#  K: 1
#  emb_dim: 8
#  hidden: 8
#  input_drop: 0.05
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
#
#AMiner:
#  K: 5
#  emb_dim: 8
#  hidden: 8
#  input_drop: 0.2
#  dropout: 0.35
#  lr: 0.008
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.3
#效果较好的 Micro mean = 95.5915 ± 0.2371  	  Macro mean =  95.2608 ± 0.2512
#DBLP:
#  K: 5
#  emb_dim: 16
#  hidden: 96
#  input_drop: 0.4
#  dropout: 0.6
#  lr: 0.002
#  wd: 0.0
#  prop_lr: 0.002
#  prop_wd: 0.8
##先使用单多项式微调路径权重再使用勒让德系数构造新的具有正交结构的非正交多项式#Micro mean = 95.5915 ± 0.2141  	  Macro mean =  95.2589 ± 0.2259
#DBLP:
#  K: 5
#  emb_dim: 16
#  hidden: 96
#  input_drop: 0.4
#  dropout: 0.1
#  lr: 0.002
#  wd: 0.0
#  prop_lr: 0.002
#  prop_wd: 0.8
##都使用单多项式微调路径权重 结果Micro mean = 95.3803 ± 0.2454  	  Macro mean =  95.0356 ± 0.2239
#DBLP:
#  K: 5
#  emb_dim: 16
#  hidden: 96
#  input_drop: 0.4
#  dropout: 0.1
#  lr: 0.002
#  wd: 0.0
#  prop_lr: 0.002
#  prop_wd: 0.8
##Micro mean = 95.5986 ± 0.0498  	  Macro mean =  95.2490 ± 0.0523
#DBLP:
#  K: 5
#  emb_dim: 16
#  hidden: 64
#  input_drop: 0.4
#  dropout: 0.1
#  lr: 0.002
#  wd: 0.0
#  prop_lr: 0.002
#  prop_wd: 0.8
##源代码的第二次更新
#DBLP:
#  K: 5
#  emb_dim: 16
#  hidden: 64
#  input_drop: 0.4
#  dropout: 0.1
#  lr: 0.006
#  wd: 0.0
#  prop_lr: 0.002
#  prop_wd: 0.8
#########Micro mean = 95.5986 ± 0.2065  	  Macro mean =  95.2691 ± 0.2067
###########用这个Micro mean = 95.7465 ± 0.1687  	  Macro mean =  95.4202 ± 0.1721 加了路径协同图后！#那个阈值影响也不大
DBLP:
  K: 5
  emb_dim: 128
  hidden: 64
  input_drop: 0.3
  dropout: 0.1
  lr: 0.002
  wd: 0.0
  prop_lr: 0.002
  prop_wd: 0.8
  threshold: 0.1
  gamma: 1
##ACM用这个跑我的
ACM:
  K: 5
  emb_dim: 128
  hidden: 32
  input_drop: 0.9
  dropout: 0.25
  lr: 0.002
  wd: 0.0002
  prop_lr: 0.02
  prop_wd: 0.9
  threshold: 1.3
  gamma: 1
#ACM:
#  K: 5
#  emb_dim: 64
#  hidden: 72
#  input_drop: 0.85
#  dropout: 0.25
#  lr: 0.004
#  wd: 0.0
#  prop_lr: 0.05
#  prop_wd: 0.8
##Micro mean = 75.2646 ± 0.2818  	  Macro mean =  73.2440 ± 0.5192
#IMDB:
#  K: 1
#  emb_dim: 256
#  hidden: 512
#  input_drop: 0.02
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
##Micro mean = 75.2682 ± 0.2848  	  Macro mean =  73.2377 ± 0.5331
#IMDB:
#  K: 1
#  emb_dim: 256
#  hidden: 512
#  input_drop: 0.05
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
##Micro mean = 75.5427 ± 0.1456  	  Macro mean =  73.6274 ± 0.2602
#IMDB:
#  K: 1
#  emb_dim: 512
#  hidden: 512
#  input_drop: 0.02
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
##Micro mean = 75.5247 ± 0.1309  	  Macro mean =  73.6248 ± 0.2508
#IMDB:
#  K: 1
#  emb_dim: 512
#  hidden: 512
#  input_drop: 0.05
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
##Micro mean = 75.7883 ± 0.3100  	  Macro mean =  73.9537 ± 0.3926
#IMDB:
#  K: 1
#  emb_dim: 512
#  hidden: 1024
#  input_drop: 0.02
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
#先使用单多项式微调路径权重再使用勒让德系数构造新的具有正交结构的非正交多项式Micro mean = 76.0556 ± 0.1669  	  Macro mean =  74.3643 ± 0.2582  Micro mean = 76.2254 ± 0.1340     Macro mean =  74.5048 ± 0.2482 Micro mean = 76.2687 ± 0.0758  	  Macro mean =  74.5701 ± 0.2096源代码在对应的这个参数下Micro mean = 75.1743 ± 0.4907  	  Macro mean =  73.2921 ± 0.7065
##@!!都使用单多项式微调路径权重 结果Micro mean = 76.3410 ± 0.1287  	  Macro mean =  74.6535 ± 0.2616
#Micro mean = 76.2651 ± 0.1621  	  Macro mean =  74.5727 ± 0.3080 0.1 #阈值的影响好像不大
#原模型使用一下参数能跑的结果Micro mean = 75.2068 ± 0.3137  	  Macro mean =  73.2602 ± 0.4747
IMDB:
  K: 1
  emb_dim: 1024
  hidden: 1024
  input_drop: 0.02
  dropout: 0.7
  lr: 0.0005
  wd: 0.0005
  prop_lr: 0.008
  prop_wd: 0.0
  threshold: 1
  gamma: 1


##Micro mean = 76.0484 ± 0.3845  	  Macro mean =  74.0319 ± 0.5576
#IMDB:
#  K: 1
#  emb_dim: 1024
#  hidden: 2048
#  input_drop: 0.02
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
##Micro mean = 75.7703 ± 0.3635  	  Macro mean =  73.9011 ± 0.4808
#IMDB:
#  K: 1
#  emb_dim: 2048
#  hidden: 2048
#  input_drop: 0.02
#  dropout: 0.7
#  lr: 0.0005
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.0
#AMiner:
#  K: 5
#  emb_dim: 64
#  hidden: 128
#  input_drop: 0.2
#  dropout: 0.35
#  lr: 0.008
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.3
#AMiner:
#  K: 6
#  emb_dim: 64
#  hidden: 32
#  input_drop: 0.2
#  dropout: 0.35
#  lr: 0.008
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.3
#AMiner:
#  K: 7
#  emb_dim: 64
#  hidden: 32
#  input_drop: 0.3
#  dropout: 0.2
#  lr: 0.008
#  wd: 0.0005
#  prop_lr: 0.008
#  prop_wd: 0.3
AMiner:
  K: 10
  emb_dim: 48
  hidden: 32
  input_drop: 0.1
  dropout: 0.1
  lr: 0.008
  wd: 0.0005
  prop_lr: 0.008
  prop_wd: 0.3
  threshold: 0.1
  gamma: 1